2021-07-12 06:04:07,607 ERROR 11724 nodejs.ClusterClientNoResponseError: client no response in 10999891ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (E:\Users\七环\Desktop\mall\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 11724
hostname: LAPTOP-F0FF6E0L

2021-07-12 06:20:11,156 ERROR 11724 nodejs.ClusterClientNoResponseError: client no response in 243214ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (E:\Users\七环\Desktop\mall\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 11724
hostname: LAPTOP-F0FF6E0L

2021-07-12 22:12:49,921 ERROR 588 [-/127.0.0.1/-/20ms GET /v1/alreadyEvaluated?page=undefined] nodejs.MongoError: Argument to $skip cannot be negative
    at Connection.<anonymous> (E:\Users\七环\Desktop\mall\server\node_modules\_mongodb@3.6.8@mongodb\lib\core\connection\pool.js:451:61)
    at Connection.emit (events.js:376:20)
    at processMessage (E:\Users\七环\Desktop\mall\server\node_modules\_mongodb@3.6.8@mongodb\lib\core\connection\connection.js:451:10)
    at Socket.<anonymous> (E:\Users\七环\Desktop\mall\server\node_modules\_mongodb@3.6.8@mongodb\lib\core\connection\connection.js:620:15)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
ok: 0
code: 15956
codeName: "Location15956"
name: "MongoError"
pid: 588
hostname: LAPTOP-F0FF6E0L

